services:
  
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ozontech
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    networks:
      - redbook
  
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: redbookdb
    ports:
      - "5432:5432"
    networks:
      - redbook
    volumes:
      - database-pg:/var/lib/postgresql/data

volumes:
  minio-storage:
  database-pg:

networks:
  redbook:
