//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Scripts.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgresUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgresUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Scripts.User.PostgresUser", typeof(PostgresUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM users
        ///WHERE user_id = @UserId.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    u.user_id           as &quot;UserId&quot;,
        ///    u.user_name         as &quot;UserName&quot;,
        ///    u.email             as &quot;Email&quot;,
        ///    u.password          as &quot;Password&quot;,
        ///    u.created_date      as &quot;CreatedDate&quot;,
        ///    u.role              as &quot;Role&quot;
        ///FROM users u.
        /// </summary>
        internal static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    u.user_id           as &quot;UserId&quot;,
        ///    u.user_name         as &quot;UserName&quot;,
        ///    u.email             as &quot;Email&quot;,
        ///    u.password          as &quot;Password&quot;,
        ///    u.created_date      as &quot;CreatedDate&quot;,
        ///    u.role              as &quot;Role&quot;
        ///FROM users u
        ///WHERE email = @Email AND password = @Password.
        /// </summary>
        internal static string GetByCredentials {
            get {
                return ResourceManager.GetString("GetByCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    u.user_id           as &quot;UserId&quot;,
        ///    u.user_name         as &quot;UserName&quot;,
        ///    u.email             as &quot;Email&quot;,
        ///    u.password          as &quot;Password&quot;,
        ///    u.created_date      as &quot;CreatedDate&quot;,
        ///    u.role              as &quot;Role&quot;
        ///FROM users u
        ///WHERE email = @Email.
        /// </summary>
        internal static string GetByEmail {
            get {
                return ResourceManager.GetString("GetByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    u.user_id           as &quot;UserId&quot;,
        ///    u.user_name         as &quot;UserName&quot;,
        ///    u.email             as &quot;Email&quot;,
        ///    u.password          as &quot;Password&quot;,
        ///    u.created_date      as &quot;CreatedDate&quot;,
        ///    u.role              as &quot;Role&quot;
        ///FROM users u
        ///WHERE user_id = @UserId.
        /// </summary>
        internal static string GetById {
            get {
                return ResourceManager.GetString("GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO users (user_name, email, password, created_date, role)
        ///VALUES (@UserName, @Email, @Password, @CreatedDate, @Role)
        ///
        ///.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE users u
        ///SET
        ///    user_name       = @UserName,
        ///    email           = @Email,
        ///    password        = @Password,
        ///    role            = @Role
        ///WHERE user_id = @UserId
        ///RETURNING
        ///    u.user_id           as &quot;UserId&quot;,
        ///    u.user_name         as &quot;UserName&quot;,
        ///    u.email             as &quot;Email&quot;,
        ///    u.password          as &quot;Password&quot;,
        ///    u.created_date      as &quot;CreatedDate&quot;,
        ///    u.role              as &quot;Role&quot;
        ///    .
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
